// flow-typed signature: 97a8c98106ae90a2d1845126336f2725
// flow-typed version: <<STUB>>/react-pdf_v^2.4.2/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-pdf'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-pdf' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-pdf/build/Document' {
  declare module.exports: any;
}

declare module 'react-pdf/build/entry' {
  declare module.exports: any;
}

declare module 'react-pdf/build/entry.noworker' {
  declare module.exports: any;
}

declare module 'react-pdf/build/entry.webpack' {
  declare module.exports: any;
}

declare module 'react-pdf/build/LinkService' {
  declare module.exports: any;
}

declare module 'react-pdf/build/Outline' {
  declare module.exports: any;
}

declare module 'react-pdf/build/Page' {
  declare module.exports: any;
}

declare module 'react-pdf/build/PageAnnotations' {
  declare module.exports: any;
}

declare module 'react-pdf/build/PageCanvas' {
  declare module.exports: any;
}

declare module 'react-pdf/build/PageSVG' {
  declare module.exports: any;
}

declare module 'react-pdf/build/PageTextContent' {
  declare module.exports: any;
}

declare module 'react-pdf/build/setOptions' {
  declare module.exports: any;
}

declare module 'react-pdf/build/shared/events' {
  declare module.exports: any;
}

declare module 'react-pdf/build/shared/propTypes' {
  declare module.exports: any;
}

declare module 'react-pdf/build/shared/util' {
  declare module.exports: any;
}

declare module 'react-pdf/src/Document' {
  declare module.exports: any;
}

declare module 'react-pdf/src/entry' {
  declare module.exports: any;
}

declare module 'react-pdf/src/entry.noworker' {
  declare module.exports: any;
}

declare module 'react-pdf/src/entry.webpack' {
  declare module.exports: any;
}

declare module 'react-pdf/src/LinkService' {
  declare module.exports: any;
}

declare module 'react-pdf/src/Outline' {
  declare module.exports: any;
}

declare module 'react-pdf/src/Page' {
  declare module.exports: any;
}

declare module 'react-pdf/src/PageAnnotations' {
  declare module.exports: any;
}

declare module 'react-pdf/src/PageCanvas' {
  declare module.exports: any;
}

declare module 'react-pdf/src/PageSVG' {
  declare module.exports: any;
}

declare module 'react-pdf/src/PageTextContent' {
  declare module.exports: any;
}

declare module 'react-pdf/src/setOptions' {
  declare module.exports: any;
}

declare module 'react-pdf/src/shared/events' {
  declare module.exports: any;
}

declare module 'react-pdf/src/shared/propTypes' {
  declare module.exports: any;
}

declare module 'react-pdf/src/shared/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-pdf/build/Document.js' {
  declare module.exports: $Exports<'react-pdf/build/Document'>;
}
declare module 'react-pdf/build/entry.js' {
  declare module.exports: $Exports<'react-pdf/build/entry'>;
}
declare module 'react-pdf/build/entry.noworker.js' {
  declare module.exports: $Exports<'react-pdf/build/entry.noworker'>;
}
declare module 'react-pdf/build/entry.webpack.js' {
  declare module.exports: $Exports<'react-pdf/build/entry.webpack'>;
}
declare module 'react-pdf/build/LinkService.js' {
  declare module.exports: $Exports<'react-pdf/build/LinkService'>;
}
declare module 'react-pdf/build/Outline.js' {
  declare module.exports: $Exports<'react-pdf/build/Outline'>;
}
declare module 'react-pdf/build/Page.js' {
  declare module.exports: $Exports<'react-pdf/build/Page'>;
}
declare module 'react-pdf/build/PageAnnotations.js' {
  declare module.exports: $Exports<'react-pdf/build/PageAnnotations'>;
}
declare module 'react-pdf/build/PageCanvas.js' {
  declare module.exports: $Exports<'react-pdf/build/PageCanvas'>;
}
declare module 'react-pdf/build/PageSVG.js' {
  declare module.exports: $Exports<'react-pdf/build/PageSVG'>;
}
declare module 'react-pdf/build/PageTextContent.js' {
  declare module.exports: $Exports<'react-pdf/build/PageTextContent'>;
}
declare module 'react-pdf/build/setOptions.js' {
  declare module.exports: $Exports<'react-pdf/build/setOptions'>;
}
declare module 'react-pdf/build/shared/events.js' {
  declare module.exports: $Exports<'react-pdf/build/shared/events'>;
}
declare module 'react-pdf/build/shared/propTypes.js' {
  declare module.exports: $Exports<'react-pdf/build/shared/propTypes'>;
}
declare module 'react-pdf/build/shared/util.js' {
  declare module.exports: $Exports<'react-pdf/build/shared/util'>;
}
declare module 'react-pdf/src/Document.jsx' {
  declare module.exports: $Exports<'react-pdf/src/Document'>;
}
declare module 'react-pdf/src/entry.js' {
  declare module.exports: $Exports<'react-pdf/src/entry'>;
}
declare module 'react-pdf/src/entry.noworker.js' {
  declare module.exports: $Exports<'react-pdf/src/entry.noworker'>;
}
declare module 'react-pdf/src/entry.webpack.js' {
  declare module.exports: $Exports<'react-pdf/src/entry.webpack'>;
}
declare module 'react-pdf/src/LinkService.js' {
  declare module.exports: $Exports<'react-pdf/src/LinkService'>;
}
declare module 'react-pdf/src/Outline.jsx' {
  declare module.exports: $Exports<'react-pdf/src/Outline'>;
}
declare module 'react-pdf/src/Page.jsx' {
  declare module.exports: $Exports<'react-pdf/src/Page'>;
}
declare module 'react-pdf/src/PageAnnotations.jsx' {
  declare module.exports: $Exports<'react-pdf/src/PageAnnotations'>;
}
declare module 'react-pdf/src/PageCanvas.jsx' {
  declare module.exports: $Exports<'react-pdf/src/PageCanvas'>;
}
declare module 'react-pdf/src/PageSVG.jsx' {
  declare module.exports: $Exports<'react-pdf/src/PageSVG'>;
}
declare module 'react-pdf/src/PageTextContent.jsx' {
  declare module.exports: $Exports<'react-pdf/src/PageTextContent'>;
}
declare module 'react-pdf/src/setOptions.js' {
  declare module.exports: $Exports<'react-pdf/src/setOptions'>;
}
declare module 'react-pdf/src/shared/events.js' {
  declare module.exports: $Exports<'react-pdf/src/shared/events'>;
}
declare module 'react-pdf/src/shared/propTypes.js' {
  declare module.exports: $Exports<'react-pdf/src/shared/propTypes'>;
}
declare module 'react-pdf/src/shared/util.js' {
  declare module.exports: $Exports<'react-pdf/src/shared/util'>;
}
